name: J2EE_Frontend CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  build-frontend:
    name: Build react-router frontend 
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun version
        run: bun --version

      - name: Install dependencies
        run: bun install

      - name: Build frontend
        run: bun run build